CREATE DATABASE VIDEOLOCADORA
GO 

USE VIDEOLOCADORA

--CRIAÇÃO DAS TABELAS

CREATE TABLE dbo.CLIENTES
(
	COD_CLIENTE NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	RG VARCHAR(9) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(50) NULL,
	BAIRRO VARCHAR(30) NULL,
	CIDADE VARCHAR(30) NULL, 
	ESTADO CHAR(2) NOT NULL,
	TELEFONE VARCHAR(15) NULL,
	EMAIL VARCHAR(30) NULL,
	DATANASCIMENTO DATETIME NULL,
	sexo char(1)
)

CREATE TABLE dbo.USUARIO
(
USUARIO VARCHAR(20) PRIMARY KEY,
SENHA VARCHAR (6) NOT NULL,
)

insert into USUARIO values ('admin','123')

CREATE TABLE dbo.CATEGORIA
(
	COD_CATEGORIA NUMERIC(10,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME_CATEGORIA VARCHAR(20) NOT NULL,
)
insert into CATEGORIA(nome_categoria) values ('Terror')

CREATE TABLE dbo.FILME
(
	COD_FILME NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FILME VARCHAR(30) NOT NULL,
	COD_CATEGORIA NUMERIC(10,0) NOT NULL,
	DIRETOR VARCHAR(50) NOT NULL,
	VALOR_LOCACAO FLOAT NOT NULL,
	RESERVADA CHAR(1) NOT NULL
)

CREATE TABLE dbo.LOCACOES
(
	COD_LOCACAO NUMERIC(18,0) IDENTITY(1,1) NOT NULL,
	COD_CLIENTE NUMERIC(18,0) NOT NULL,
	COD_FILME NUMERIC(18,0) NOT NULL,
	DATA_RETIRADA DATETIME NOT NULL,
	DATA_DEVOLUCAO DATETIME NULL,
	CONSTRAINT PK_LOCACAO_CLIENTE PRIMARY KEY(COD_LOCACAO, COD_CLIENTE, COD_FILME)
)


--CRIAÇÃO DOS RELACIONAMENTOS 
--LOCACAO - CLIENTES
ALTER TABLE dbo.LOCACOES WITH CHECK ADD CONSTRAINT FK_LOCACOES_CLIENTE FOREIGN KEY (COD_CLIENTE)
REFERENCES dbo.CLIENTES(COD_CLIENTE)
GO

ALTER TABLE dbo.LOCACOES CHECK CONSTRAINT FK_LOCACOES_CLIENTE 
GO


-- LOCACOES - FILME
ALTER TABLE dbo.LOCACOES WITH CHECK ADD CONSTRAINT FK_LOCACOES_FILME FOREIGN KEY (COD_FILME)
REFERENCES dbo.FILME(COD_FILME)
GO

ALTER TABLE dbo.LOCACOES CHECK CONSTRAINT FK_LOCACOES_FILME 
GO

--FILME - CATEGORIA
ALTER TABLE dbo.FILME WITH CHECK ADD CONSTRAINT FK_CATEGORIA_FILME FOREIGN KEY (COD_CATEGORIA)
REFERENCES dbo.CATEGORIA(COD_CATEGORIA)
GO

ALTER TABLE dbo.FILME CHECK CONSTRAINT FK_CATEGORIA_FILME
GO


ALTER TABLE locacoes add valor_total money
GO