CREATE DATABASE SIGLI
-- go 

USE SIGLI
-- go

CREATE TABLE dbo.USUARIO
(
USUARIO varchar(50)PRIMARY KEY NOT NULL,
SENHA varchar(13)NOT NULL,
NIVEL varchar (1)NOT NULL,
NOME varchar (50) NOT NULL,
COD_TURMA numeric (18,0),
RA varchar (13),
IDADE varchar (3),
)

CREATE TABLE dbo.LOGIN
(
COD_LOG numeric(18,0) identity(1,1) primary key NOT NULL,
USUARIO varchar(50)NOT NULL,
MICRO varchar (50) NOT NULL,
HORAENTRADA varchar NULL,
HORASAIDA varchar NULL,
)

CREATE TABLE dbo.LABORATORIO
(
COD_LAB numeric(18,0) identity(1,1) primary key NOT NULL,
NOMELAB varchar(50)NOT NULL,
) 


create TABLE dbo.MICRO
(
NOMEMICRO VARCHAR (50) PRIMARY KEY NOT NULL,
IP VARCHAR (15) NOT NULL,
LAB	numeric (18,0) NOT NULL,
)


create TABLE dbo.RESTRICAO
(
COD_RES	NUMERIC(18,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
LAB numeric (18,0) NOT NULL,
COMANDO VARCHAR (50) NOT NULL,
)

CREATE TABLE dbo.TURMA
(
COD_TURMA NUMERIC (18,0)IDENTITY(1,1)PRIMARY KEY,
TURMA VARCHAR (20),
PERIODO VARCHAR (20),
)
--RELACIONAMNETO

--TABELA LOGIN --TABELA MICRO 
ALTER TABLE [dbo].[LOGIN]  WITH CHECK ADD  CONSTRAINT [FK_LOGIN_MICRO] FOREIGN KEY([MICRO])
REFERENCES [dbo].[MICRO] ([NOMEMICRO])
GO
ALTER TABLE [dbo].[LOGIN] CHECK CONSTRAINT [FK_LOGIN_MICRO]
GO
--TABELA LOGIN --TABELA USUARIO
ALTER TABLE [dbo].[LOGIN]  WITH CHECK ADD  CONSTRAINT [FK_LOGIN_USUARIO] FOREIGN KEY([USUARIO])
REFERENCES [dbo].[USUARIO] ([USUARIO])
GO
ALTER TABLE [dbo].[LOGIN] CHECK CONSTRAINT [FK_LOGIN_USUARIO]
GO
--TABELA MICRO --TABELA LABORATORIO
ALTER TABLE [dbo].[MICRO]  WITH CHECK ADD  CONSTRAINT [FK_MICRO_LABORATORIO] FOREIGN KEY([LAB])
REFERENCES [dbo].[LABORATORIO] ([COD_LAB])
GO
ALTER TABLE [dbo].[MICRO] CHECK CONSTRAINT [FK_MICRO_LABORATORIO]
GO
--TABELA RESTRICAO -- TABELA LABORATORIO
ALTER TABLE [dbo].[RESTRICAO]  WITH CHECK ADD  CONSTRAINT [FK_RESTRICAO_LABORATORIO] FOREIGN KEY([LAB])
REFERENCES [dbo].[LABORATORIO] ([COD_LAB])
GO
ALTER TABLE [dbo].[RESTRICAO] CHECK CONSTRAINT [FK_RESTRICAO_LABORATORIO]
GO
--TABELA USUARIO --TABELA TURMA
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_TURMA] FOREIGN KEY([COD_TURMA])
REFERENCES [dbo].[TURMA] ([COD_TURMA])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_TURMA]
GO
